# -*- coding: utf-8 -*-
"""inbreast-train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B9hku0Y_3BlOnluRBJ3Lg9F5fXTkxJ9h
"""

"""
INBreast Mass Detection - Complete Training Pipeline
=====================================================
Deep learning model for detecting masses in mammography images using ResNet34
with advanced preprocessing (CLAHE + Unsharp Masking) and Focal Loss.

Author: [Your Name]
Date: 2025-02-05
Dataset: INBreast
Architecture: ResNet34 with Focal Loss
Preprocessing: CLAHE + Unsharp Masking

Usage:
    python train_inbreast.py --excel_path /path/to/INBreast.xlsx --img_dir /path/to/images
"""

import os
import random
import argparse
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.models as models
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
from torch.utils.data import Dataset, DataLoader
import albumentations as A
from albumentations.pytorch import ToTensorV2
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
import warnings
from imageio.v2 import imread
import cv2

warnings.filterwarnings('ignore')


# ============================================================================
# GLOBAL CONFIGURATION
# ============================================================================
SEED = 42
MEAN, STD = 0.3286, 0.0379  # Computed from INBreast dataset
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')


# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================
def seed_everything(seed):
    """Set random seeds for reproducibility"""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False


def apply_clahe(img):
    """Apply Contrast Limited Adaptive Histogram Equalization"""
    clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
    return clahe.apply(img)


def apply_histogram_equalization(img):
    """Apply standard histogram equalization"""
    return cv2.equalizeHist(img)


def apply_unsharp_mask(img):
    """Apply unsharp masking for edge enhancement"""
    gaussian = cv2.GaussianBlur(img, (5, 5), 2.0)
    sharpened = cv2.addWeighted(img, 1.5, gaussian, -0.5, 0)
    return np.clip(sharpened, 0, 255).astype(np.uint8)


def preprocess_image_advanced(img):
    """
    Main preprocessing pipeline: Min-Max normalization + CLAHE + Unsharp Masking

    Args:
        img: Input grayscale image (any dtype)

    Returns:
        Preprocessed image (uint8)
    """
    # Step 1: Min-Max normalization to [0, 255]
    img_norm = ((img - img.min()) / (img.max() - img.min() + 1e-8) * 255).astype(np.uint8)

    # Step 2: CLAHE for local contrast enhancement
    img_clahe = apply_clahe(img_norm)

    # Step 3: Unsharp masking for edge enhancement
    img_sharp = apply_unsharp_mask(img_clahe)

    return img_sharp


# ============================================================================
# DATA AUGMENTATION
# ============================================================================
def get_transforms(train=True, augment=True):
    """
    Get image transformations for training or validation

    Args:
        train: Whether these are training transforms
        augment: Whether to apply data augmentation

    Returns:
        Albumentations composition of transforms
    """
    transforms_list = [A.Resize(448, 448)]

    if train and augment:
        transforms_list += [
            A.HorizontalFlip(p=0.5),
            A.VerticalFlip(p=0.3),
            A.ShiftScaleRotate(shift_limit=0.1, scale_limit=0.15, rotate_limit=20, p=0.6),
            A.RandomBrightnessContrast(brightness_limit=0.3, contrast_limit=0.3, p=0.5),
            A.GaussNoise(var_limit=(10.0, 50.0), p=0.3),
            A.ElasticTransform(alpha=1, sigma=50, p=0.3),
        ]

    transforms_list += [
        A.Normalize(mean=MEAN, std=STD),
        ToTensorV2()
    ]

    return A.Compose(transforms_list)


# ============================================================================
# DATASET CLASS
# ============================================================================
class INBreastDataset(Dataset):
    """
    Custom dataset for INBreast mammography images with advanced preprocessing
    """

    def __init__(self, df, img_dir, transform=None):
        """
        Args:
            df: DataFrame with columns ['File Name', 'Patient ID', 'Laterality', 'View', 'label']
            img_dir: Directory containing images
            transform: Albumentations transforms
        """
        self.df = df.reset_index(drop=True)
        self.img_dir = img_dir
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]

        # Construct filename
        fname = f"{int(row['File Name'])}_{row['Patient ID']}_MG_{row['Laterality']}_{row['View']}.png"
        img_path = os.path.join(self.img_dir, fname)

        # Load image
        img = imread(img_path)

        # Apply advanced preprocessing (CLAHE + Unsharp Masking)
        img_processed = preprocess_image_advanced(img)

        # Convert to 3 channels for pretrained models
        image = np.stack((img_processed, img_processed, img_processed), axis=2)

        # Flip right laterality images for consistency
        if row['Laterality'] == 'R':
            image = np.fliplr(image).copy()

        # Apply augmentations and normalization
        if self.transform:
            image = self.transform(image=image)['image']

        label = torch.tensor(row['label'], dtype=torch.long)

        return image, label


# ============================================================================
# FOCAL LOSS
# ============================================================================
class FocalLoss(nn.Module):
    """
    Focal Loss for addressing class imbalance
    Reference: Lin et al., "Focal Loss for Dense Object Detection", ICCV 2017
    """

    def __init__(self, alpha=0.25, gamma=2.0, weight=None):
        super(FocalLoss, self).__init__()
        self.alpha = alpha
        self.gamma = gamma
        self.weight = weight

    def forward(self, inputs, targets):
        ce_loss = F.cross_entropy(inputs, targets, reduction='none', weight=self.weight)
        pt = torch.exp(-ce_loss)
        focal_loss = self.alpha * (1 - pt) ** self.gamma * ce_loss
        return focal_loss.mean()


# ============================================================================
# DATA LOADING
# ============================================================================
def load_data(excel_path, img_dir):
    """Load and prepare dataset from Excel file"""
    print("=" * 80)
    print("1️⃣  LOADING DATA")
    print("=" * 80)

    if not os.path.exists(excel_path):
        raise FileNotFoundError(f"Excel file not found: {excel_path}")

    df = pd.read_excel(excel_path)
    df['label'] = (df['Mass '] == 1).astype(int)

    def exists(row):
        try:
            fname = f"{int(row['File Name'])}_{row['Patient ID']}_MG_{row['Laterality']}_{row['View']}.png"
            return os.path.isfile(os.path.join(img_dir, fname))
        except:
            return False

    df['exists'] = df.apply(exists, axis=1)
    df = df[df['exists']].reset_index(drop=True)

    print(f"✓ Loaded {len(df)} images from {df['Patient ID'].nunique()} patients")
    print(f"\nClass Distribution:")
    print(f"  0 (No Mass):  {(df['label']==0).sum()} images")
    print(f"  1 (Has Mass): {(df['label']==1).sum()} images")

    return df


# ============================================================================
# PREPROCESSING VISUALIZATION
# ============================================================================
def visualize_preprocessing(df, img_dir, seed=42):
    """Visualize the preprocessing pipeline on sample images"""
    print("\n" + "=" * 80)
    print("🔍 PREPROCESSING VISUALIZATION")
    print("=" * 80)

    os.makedirs('results', exist_ok=True)

    # Sample one image from each class
    samples = pd.concat([
        df[df['label'] == 0].sample(1, random_state=seed),
        df[df['label'] == 1].sample(1, random_state=seed)
    ])

    for idx, (_, row) in enumerate(samples.iterrows()):
        fname = f"{int(row['File Name'])}_{row['Patient ID']}_MG_{row['Laterality']}_{row['View']}.png"
        img_original = imread(os.path.join(img_dir, fname))

        label_name = 'No Mass' if row['label'] == 0 else 'Has Mass'

        # Apply different techniques
        img_norm = ((img_original - img_original.min()) / (img_original.max() - img_original.min() + 1e-8) * 255).astype(np.uint8)
        img_hist = apply_histogram_equalization(img_norm)
        img_clahe = apply_clahe(img_norm)
        img_sharp = apply_unsharp_mask(img_clahe)

        fig, axes = plt.subplots(2, 3, figsize=(18, 12))

        axes[0, 0].imshow(img_original, cmap='gray')
        axes[0, 0].set_title(f'1. ORIGINAL\n{label_name}\nmin={img_original.min()}, max={img_original.max()}', fontsize=11)
        axes[0, 0].axis('off')

        axes[0, 1].imshow(img_norm, cmap='gray')
        axes[0, 1].set_title(f'2. MIN-MAX NORM [0-255]\nunique={len(np.unique(img_norm))}', fontsize=11)
        axes[0, 1].axis('off')

        axes[0, 2].imshow(img_hist, cmap='gray')
        axes[0, 2].set_title(f'3. HISTOGRAM EQUALIZATION\nGlobal contrast', fontsize=11)
        axes[0, 2].axis('off')

        axes[1, 0].imshow(img_clahe, cmap='gray')
        axes[1, 0].set_title(f'4. CLAHE\nLocal contrast (BEST!)', fontsize=11, fontweight='bold', color='green')
        axes[1, 0].axis('off')

        axes[1, 1].imshow(img_sharp, cmap='gray')
        axes[1, 1].set_title(f'5. CLAHE + UNSHARP MASK\nEnhanced edges', fontsize=11, fontweight='bold', color='blue')
        axes[1, 1].axis('off')

        # Histogram comparison
        axes[1, 2].hist(img_sharp.flatten(), bins=50, color='purple', alpha=0.7, label='Final')
        axes[1, 2].hist(img_norm.flatten(), bins=50, color='gray', alpha=0.3, label='Original norm')
        axes[1, 2].set_title('6. HISTOGRAM\nFinal vs Original', fontsize=11)
        axes[1, 2].legend()

        plt.suptitle(f'PREPROCESSING PIPELINE - {label_name}', fontsize=14, fontweight='bold', y=0.98)
        plt.tight_layout()
        plt.savefig(f'results/preprocessing_{label_name.replace(" ", "_")}.png', dpi=150, bbox_inches='tight')
        plt.close()

        print(f"\n{label_name}:")
        print(f"  Original:     unique={len(np.unique(img_original))}, range=[{img_original.min()}, {img_original.max()}]")
        print(f"  CLAHE+Sharp:  unique={len(np.unique(img_sharp))}, range=[{img_sharp.min()}, {img_sharp.max()}]")
        print(f"  Contrast boost: {len(np.unique(img_sharp)) / len(np.unique(img_norm)):.2f}x")


# ============================================================================
# DATA SPLITTING
# ============================================================================
def split_data(df, seed=42):
    """Split data by patient ID to prevent data leakage"""
    print("\n" + "=" * 80)
    print("3️⃣ DATA SPLITTING: 80/10/10")
    print("=" * 80)

    patients = df['Patient ID'].unique()
    train_pts, temp_pts = train_test_split(patients, test_size=0.2, random_state=seed)
    val_pts, test_pts = train_test_split(temp_pts, test_size=0.5, random_state=seed)

    train_df = df[df['Patient ID'].isin(train_pts)].reset_index(drop=True)
    val_df = df[df['Patient ID'].isin(val_pts)].reset_index(drop=True)
    test_df = df[df['Patient ID'].isin(test_pts)].reset_index(drop=True)

    print(f"Train: {len(train_df)} images - {dict(train_df['label'].value_counts().sort_index())}")
    print(f"Val:   {len(val_df)} images - {dict(val_df['label'].value_counts().sort_index())}")
    print(f"Test:  {len(test_df)} images - {dict(test_df['label'].value_counts().sort_index())}")

    return train_df, val_df, test_df


# ============================================================================
# AUGMENTATION VISUALIZATION
# ============================================================================
def visualize_augmentations(dataset, n_samples=8):
    """Visualize augmented training samples"""
    print("\n" + "=" * 80)
    print("🔍 AUGMENTATION VISUALIZATION")
    print("=" * 80)

    os.makedirs('results', exist_ok=True)

    loader = DataLoader(dataset, batch_size=n_samples, shuffle=True)
    images_batch, labels_batch = next(iter(loader))

    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    axes = axes.flatten()

    for i in range(n_samples):
        img_tensor = images_batch[i]

        # Denormalize for display
        img_denorm = img_tensor * STD + MEAN
        img_denorm = img_denorm.clamp(0, 1)
        img_np = img_denorm.permute(1, 2, 0).numpy()

        label_name = 'No Mass' if labels_batch[i].item() == 0 else 'Has Mass'

        axes[i].imshow(img_np[:, :, 0], cmap='gray')
        axes[i].set_title(f"{label_name}\nTensor: [{img_tensor.min():.2f}, {img_tensor.max():.2f}]", fontsize=10)
        axes[i].axis('off')

    plt.suptitle('Training Samples with Augmentations and CLAHE Preprocessing', fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig('results/augmented_samples.png', dpi=150, bbox_inches='tight')
    plt.close()
    print("✓ Augmentation visualization saved")


# ============================================================================
# SANITY CHECK
# ============================================================================
def sanity_check(train_df, img_dir, device, seed=42):
    """Quick sanity check: can model overfit on 10 samples?"""
    print("\n" + "=" * 80)
    print("6️⃣ SANITY CHECK: 10 images")
    print("=" * 80)

    sanity_train = pd.concat([
        train_df[train_df['label'] == 0].head(5),
        train_df[train_df['label'] == 1].head(5)
    ]).reset_index(drop=True)

    sanity_ds = INBreastDataset(sanity_train, img_dir, transform=get_transforms(train=False, augment=False))
    sanity_loader = DataLoader(sanity_ds, batch_size=10, shuffle=False)

    model = models.resnet34(pretrained=True)
    model.fc = nn.Linear(512, 2)
    model = model.to(device)

    optimizer = torch.optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
    criterion = nn.CrossEntropyLoss()

    print(f"Sanity dataset: {len(sanity_train)} images")

    first_100 = None
    consecutive_100 = 0
    max_consecutive = 0

    for epoch in range(1, 51):
        model.train()
        total_loss, correct, total = 0, 0, 0

        for images, labels in sanity_loader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item() * images.size(0)
            _, preds = outputs.max(1)
            total += labels.size(0)
            correct += preds.eq(labels).sum().item()

        acc = 100. * correct / total

        if acc == 100.0:
            if first_100 is None:
                first_100 = epoch
            consecutive_100 += 1
            max_consecutive = max(max_consecutive, consecutive_100)
        else:
            consecutive_100 = 0

        if epoch % 10 == 0 or epoch <= 5 or epoch == 50:
            print(f"Epoch {epoch:02d}/50 | Loss: {total_loss/total:.4f} | Acc: {acc:.1f}%")

    print()
    if first_100 is not None and max_consecutive >= 10:
        print(f"✅ SANITY CHECK PASSED! (epoch {first_100}, stability {max_consecutive})")
    else:
        print(f"⚠️ SANITY CHECK WARNING: max_acc={acc:.1f}%")

    del model, optimizer, criterion
    torch.cuda.empty_cache()


# ============================================================================
# MODEL CREATION
# ============================================================================
def create_model(device):
    """Create ResNet34 model with dropout"""
    print("\n" + "=" * 80)
    print("7️⃣ CREATING MODEL - ResNet34")
    print("=" * 80)

    model = models.resnet34(pretrained=True)

    # Fine-tune all layers
    for param in model.parameters():
        param.requires_grad = True

    # Replace final layer with dropout
    model.fc = nn.Sequential(
        nn.Dropout(0.5),
        nn.Linear(512, 2)
    )

    model = model.to(device)
    print("✓ ResNet34 loaded with dropout regularization")

    return model


# ============================================================================
# TRAINING LOOP
# ============================================================================
def train_model(model, train_loader, val_loader, criterion, optimizer, scheduler,
                device, epochs=80):
    """Train the model"""
    print("\n" + "=" * 80)
    print(f"8️⃣ TRAINING: {epochs} epochs with Focal Loss")
    print("=" * 80)

    history = {
        'train_loss': [], 'train_acc': [], 'train_f1': [],
        'val_loss': [], 'val_acc': [], 'val_f1': []
    }
    best_val_f1 = 0
    best_model_state = None
    best_epoch = 0

    for epoch in range(1, epochs + 1):
        # TRAIN
        model.train()
        train_loss, correct, total = 0, 0, 0
        train_preds_list, train_labels_list = [], []

        pbar = tqdm(train_loader, desc=f"Epoch {epoch}/{epochs}", leave=False)
        for images, labels in pbar:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            outputs = model(images)
            loss = criterion(outputs, labels)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            train_loss += loss.item() * images.size(0)
            _, preds = outputs.max(1)
            total += labels.size(0)
            correct += preds.eq(labels).sum().item()

            train_preds_list.extend(preds.cpu().numpy())
            train_labels_list.extend(labels.cpu().numpy())

            pbar.set_postfix({'loss': f'{loss.item():.3f}'})

        train_loss /= total
        train_acc = 100. * correct / total
        train_f1 = f1_score(train_labels_list, train_preds_list, average='binary', zero_division=0)

        # VALIDATION
        model.eval()
        val_loss, val_correct, val_total = 0, 0, 0
        val_preds_list, val_labels_list = [], []

        with torch.no_grad():
            for images, labels in val_loader:
                images, labels = images.to(device), labels.to(device)
                outputs = model(images)
                loss = criterion(outputs, labels)

                val_loss += loss.item() * images.size(0)
                _, preds = outputs.max(1)
                val_total += labels.size(0)
                val_correct += preds.eq(labels).sum().item()

                val_preds_list.extend(preds.cpu().numpy())
                val_labels_list.extend(labels.cpu().numpy())

        val_loss /= val_total
        val_acc = 100. * val_correct / val_total
        val_f1 = f1_score(val_labels_list, val_preds_list, average='binary', zero_division=0)

        scheduler.step()

        # Save best model
        if val_f1 > best_val_f1:
            best_val_f1 = val_f1
            best_epoch = epoch
            best_model_state = {k: v.cpu().clone() for k, v in model.state_dict().items()}

        # Update history
        history['train_loss'].append(train_loss)
        history['train_acc'].append(train_acc)
        history['train_f1'].append(train_f1)
        history['val_loss'].append(val_loss)
        history['val_acc'].append(val_acc)
        history['val_f1'].append(val_f1)

        # Print progress
        unique_val = len(set(val_preds_list))
        status = "✓" if unique_val > 1 else f"⚠️ Only {unique_val} class"

        print(f"E{epoch:02d} | TrL:{train_loss:.3f} TrA:{train_acc:5.1f}% TrF1:{train_f1:.3f} | "
              f"VaL:{val_loss:.3f} VaA:{val_acc:5.1f}% VaF1:{val_f1:.3f} {status}")

    print(f"\n🏆 Best model: epoch {best_epoch}, val_f1={best_val_f1:.4f}")

    # Load best model
    model.load_state_dict(best_model_state)

    # Save model
    os.makedirs('models', exist_ok=True)
    torch.save({
        'epoch': best_epoch,
        'model_state_dict': best_model_state,
        'val_f1': best_val_f1,
        'history': history
    }, 'models/best_model.pth')
    print(f"✓ Model saved to models/best_model.pth")

    return model, history, best_epoch


# ============================================================================
# EVALUATION
# ============================================================================
def evaluate_model(model, test_loader, device):
    """Evaluate model on test set"""
    print("\n" + "=" * 80)
    print("9️⃣ TEST EVALUATION")
    print("=" * 80)

    model.eval()
    test_preds, test_labels = [], []

    with torch.no_grad():
        for images, labels in test_loader:
            outputs = model(images.to(device))
            preds = outputs.argmax(1).cpu().numpy()
            test_preds.extend(preds)
            test_labels.extend(labels.numpy())

    test_acc = accuracy_score(test_labels, test_preds)
    test_f1 = f1_score(test_labels, test_preds, average='binary')

    print(f"\n🎯 FINAL RESULTS:")
    print(f"Test Accuracy: {test_acc*100:.2f}%")
    print(f"Test F1 Score: {test_f1:.4f}\n")

    class_names = ['No Mass', 'Has Mass']
    print(classification_report(test_labels, test_preds, target_names=class_names, digits=4))

    # Confusion Matrix
    os.makedirs('results', exist_ok=True)
    cm = confusion_matrix(test_labels, test_preds)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names)
    plt.title(f'Test Confusion Matrix\nAcc: {test_acc*100:.2f}% | F1: {test_f1:.4f}', fontweight='bold')
    plt.ylabel('True')
    plt.xlabel('Predicted')
    plt.tight_layout()
    plt.savefig('results/confusion_matrix.png', dpi=300, bbox_inches='tight')
    plt.close()

    return test_acc, test_f1, test_preds, test_labels


# ============================================================================
# VISUALIZATION
# ============================================================================
def plot_training_curves(history, best_epoch):
    """Plot training and validation metrics"""
    os.makedirs('results', exist_ok=True)

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))

    # Loss
    axes[0].plot(history['train_loss'], 'b-', label='Train', linewidth=2)
    axes[0].plot(history['val_loss'], 'r-', label='Val', linewidth=2)
    axes[0].axvline(best_epoch-1, color='g', linestyle='--', alpha=0.5, label='Best')
    axes[0].set_title('Loss', fontweight='bold', fontsize=14)
    axes[0].set_xlabel('Epoch')
    axes[0].set_ylabel('Loss')
    axes[0].legend()
    axes[0].grid(alpha=0.3)

    # Accuracy
    axes[1].plot(history['train_acc'], 'b-', label='Train', linewidth=2)
    axes[1].plot(history['val_acc'], 'r-', label='Val', linewidth=2)
    axes[1].axvline(best_epoch-1, color='g', linestyle='--', alpha=0.5, label='Best')
    axes[1].set_title('Accuracy', fontweight='bold', fontsize=14)
    axes[1].set_xlabel('Epoch')
    axes[1].set_ylabel('Accuracy (%)')
    axes[1].legend()
    axes[1].grid(alpha=0.3)

    # F1 Score
    axes[2].plot(history['train_f1'], 'b-', label='Train', linewidth=2)
    axes[2].plot(history['val_f1'], 'r-', label='Val', linewidth=2)
    axes[2].axvline(best_epoch-1, color='g', linestyle='--', alpha=0.5, label='Best')
    axes[2].axhline(0.75, color='orange', linestyle='--', alpha=0.5, label='Target')
    axes[2].set_title('F1 Score', fontweight='bold', fontsize=14)
    axes[2].set_xlabel('Epoch')
    axes[2].set_ylabel('F1 Score')
    axes[2].legend()
    axes[2].grid(alpha=0.3)

    plt.tight_layout()
    plt.savefig('results/training_curves.png', dpi=300, bbox_inches='tight')
    plt.close()
    print("✓ Training curves saved to results/training_curves.png")


def visualize_predictions(model, test_df, img_dir, device, seed=42, n_samples=8):
    """Visualize model predictions on test samples"""
    print("\n" + "=" * 80)
    print("🔍 TEST PREDICTIONS VISUALIZATION")
    print("=" * 80)

    os.makedirs('results', exist_ok=True)

    test_samples = test_df.sample(n_samples, random_state=seed)
    test_sample_ds = INBreastDataset(test_samples, img_dir, transform=get_transforms(train=False, augment=False))
    test_sample_loader = DataLoader(test_sample_ds, batch_size=n_samples, shuffle=False)

    images_test, labels_test = next(iter(test_sample_loader))

    model.eval()
    with torch.no_grad():
        outputs = model(images_test.to(device))
        probs = torch.softmax(outputs, dim=1)
        preds = outputs.argmax(1).cpu().numpy()

    fig, axes = plt.subplots(2, 4, figsize=(16, 8))
    axes = axes.flatten()

    class_names = ['No Mass', 'Has Mass']

    for i in range(n_samples):
        # Denormalize image
        img_denorm = images_test[i] * STD + MEAN
        img_denorm = img_denorm.clamp(0, 1)
        img_np = img_denorm.permute(1, 2, 0).numpy()

        true_label = labels_test[i].item()
        pred_label = preds[i]
        confidence = probs[i][pred_label].item() * 100

        color = 'green' if true_label == pred_label else 'red'

        axes[i].imshow(img_np[:, :, 0], cmap='gray')
        axes[i].set_title(f"True: {class_names[true_label]}\nPred: {class_names[pred_label]} ({confidence:.1f}%)",
                         color=color, fontweight='bold')
        axes[i].axis('off')

    plt.tight_layout()
    plt.savefig('results/test_predictions.png', dpi=150, bbox_inches='tight')
    plt.close()
    print("✓ Prediction visualization saved to results/test_predictions.png")


# ============================================================================
# MAIN FUNCTION
# ============================================================================
def main(args):
    """Main training pipeline"""
    # Setup
    print(f"Using device: {device}")
    seed_everything(args.seed)

    # Create output directories
    os.makedirs('results', exist_ok=True)
    os.makedirs('models', exist_ok=True)

    # Load data
    df = load_data(args.excel_path, args.img_dir)

    # Visualize preprocessing (optional)
    if args.visualize:
        visualize_preprocessing(df, args.img_dir, args.seed)

    # Split data
    train_df, val_df, test_df = split_data(df, args.seed)

    # Sanity check (optional)
    if args.sanity_check:
        sanity_check(train_df, args.img_dir, device, args.seed)

    # Compute class weights
    print("\n" + "=" * 80)
    print("5️⃣ CLASS WEIGHTS")
    print("=" * 80)

    class_weights = compute_class_weight(
        'balanced',
        classes=np.unique(train_df['label']),
        y=train_df['label']
    )
    class_weights = torch.FloatTensor(class_weights).to(device)

    print(f"Class 0 (No Mass):  {class_weights[0]:.4f}")
    print(f"Class 1 (Has Mass): {class_weights[1]:.4f}")
    print(f"Ratio: {class_weights[1]/class_weights[0]:.2f}x")

    # Create datasets
    train_ds = INBreastDataset(train_df, args.img_dir, transform=get_transforms(train=True, augment=True))
    val_ds = INBreastDataset(val_df, args.img_dir, transform=get_transforms(train=False, augment=False))
    test_ds = INBreastDataset(test_df, args.img_dir, transform=get_transforms(train=False, augment=False))

    train_loader = DataLoader(train_ds, batch_size=args.batch_size, shuffle=True,
                              num_workers=args.num_workers, pin_memory=True)
    val_loader = DataLoader(val_ds, batch_size=args.batch_size, shuffle=False,
                           num_workers=args.num_workers, pin_memory=True)
    test_loader = DataLoader(test_ds, batch_size=16, shuffle=False)

    print(f"\nTrain: {len(train_ds)} images")
    print(f"Val:   {len(val_ds)} images")
    print(f"Test:  {len(test_ds)} images")

    # Visualize augmentations (optional)
    if args.visualize:
        visualize_augmentations(train_ds, n_samples=8)

    # Create model
    model = create_model(device)

    # Setup training
    print(f"🔥 Using FOCAL LOSS (alpha=0.25, gamma=2.0)")
    criterion = FocalLoss(alpha=0.25, gamma=2.0, weight=class_weights)

    optimizer = torch.optim.AdamW([
        {'params': model.layer4.parameters(), 'lr': 5e-4},
        {'params': model.layer3.parameters(), 'lr': 2e-4},
        {'params': model.layer2.parameters(), 'lr': 1e-4},
        {'params': model.fc.parameters(), 'lr': 1e-3}
    ], weight_decay=1e-4)

    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=args.epochs, eta_min=1e-6
    )

    # Train
    model, history, best_epoch = train_model(
        model, train_loader, val_loader, criterion, optimizer, scheduler,
        device, epochs=args.epochs
    )

    # Plot training curves
    plot_training_curves(history, best_epoch)

    # Evaluate
    test_acc, test_f1, test_preds, test_labels = evaluate_model(model, test_loader, device)

    # Visualize predictions (optional)
    if args.visualize:
        visualize_predictions(model, test_df, args.img_dir, device, args.seed)

    # Final message
    print("\n" + "=" * 80)
    print("✅ TRAINING COMPLETE WITH CLAHE + UNSHARP MASKING!")
    print("=" * 80)
    print(f"🎯 Test F1:  {test_f1:.4f}")
    print(f"🎯 Test Acc: {test_acc*100:.2f}%")
    if test_f1 >= 0.85:
        print("🎉 EXCELLENT RESULTS!")
    elif test_f1 >= 0.75:
        print("✓ Good results!")
    else:
        print("⚠️ Room for improvement - consider stronger augmentations")
    print("=" * 80)


# ============================================================================
# ENTRY POINT
# ============================================================================
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Train INBreast mass detection model')

    # Data paths
    parser.add_argument('--excel_path', type=str, required=True,
                       help='Path to Excel file with labels (e.g., /path/to/INBreast.xlsx)')
    parser.add_argument('--img_dir', type=str, required=True,
                       help='Directory containing images (e.g., /path/to/sample_data/images)')

    # Training parameters
    parser.add_argument('--epochs', type=int, default=80,
                       help='Number of training epochs (default: 80)')
    parser.add_argument('--batch_size', type=int, default=32,
                       help='Batch size for training (default: 32)')
    parser.add_argument('--num_workers', type=int, default=2,
                       help='Number of data loading workers (default: 2)')

    # Other options
    parser.add_argument('--seed', type=int, default=42,
                       help='Random seed for reproducibility (default: 42)')
    parser.add_argument('--sanity_check', action='store_true',
                       help='Run sanity check before training')
    parser.add_argument('--visualize', action='store_true',
                       help='Generate visualization plots')

    args = parser.parse_args()

    print("\n" + "=" * 80)
    print("INBreast Mass Detection - Training Pipeline")
    print("=" * 80)
    print(f"Excel path:  {args.excel_path}")
    print(f"Image dir:   {args.img_dir}")
    print(f"Epochs:      {args.epochs}")
    print(f"Batch size:  {args.batch_size}")
    print(f"Device:      {device}")
    print("=" * 80 + "\n")

    main(args)